// web/src/App.svelte
<script lang="ts">
  import logo from './assets/svelte.png'
  import Counter from './lib/Counter.svelte'

  // Import our client
  import { OpenAPI, WeatherForecast, WeatherForecastService } from '../references/codegen/index'

  OpenAPI.BASE = "https://localhost:7277"; // Set this to match your local API endpoint.

  // Async function
  async function loadForecast(): Promise<WeatherForecast[]> {
    return await WeatherForecastService.getWeatherForecast();
  }

  // Promise
  let forecast = loadForecast();
</script>

<main>
  <img src={logo} alt="Svelte Logo" />
  <h1>Hello Typescript!</h1>

  <Counter />

  {#await forecast}
      <p>Loading forecast...</p>
  {:then days}
      { #each days as day}
          <p>{ day.summary }</p>
      {/each}
  {/await}

  <p>
    Visit <a href="https://svelte.dev">svelte.dev</a> to learn how to build Svelte
    apps.
  </p>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme">SvelteKit</a> for
    the officially supported framework, also powered by Vite!
  </p>
</main>

<style>
  :root {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
      Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  }

  main {
    text-align: center;
    padding: 1em;
    margin: 0 auto;
  }

  img {
    height: 16rem;
    width: 16rem;
  }

  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4rem;
    font-weight: 100;
    line-height: 1.1;
    margin: 2rem auto;
    max-width: 14rem;
  }

  p {
    max-width: 14rem;
    margin: 1rem auto;
    line-height: 1.35;
  }

  @media (min-width: 480px) {
    h1 {
      max-width: none;
    }

    p {
      max-width: none;
    }
  }
</style>

// web-vue/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup
import HelloWorld from './components/HelloWorld.vue'
import  { ref, onBeforeMount } from 'vue'

// Import our client
import {
  OpenAPI,
  WeatherForecast,
  WeatherForecastService,
} from "../../web/references/codegen/index";

OpenAPI.BASE = "https://localhost:7277"; // Set this to match your local API endpoint.

let forecast = ref<WeatherForecast[]>();

// onBeforeMount( async () => {
//   forecast.value = await WeatherForecastService.getWeatherForecast();
// });

const loadForecast = async() => forecast.value = await WeatherForecastService.getWeatherForecast();

loadForecast();
</script>

<template>
  <div>
    <img alt="Vue logo" src="./assets/logo.png" />
    <HelloWorld msg="Hello Vue 3 + TypeScript + Vite" />
    <p v-for="day in forecast" :key="day.date">
      {{ day.summary }}
    </p>
  </div>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
